source: .
destination:        ./_site
includes:           ./_includes
highlight:           pygments

# Setup
title:               CivicDataLab
tagline:             Data|Tech|Design|Social Science
url:                 https://civicdatalab.in
baseurl:             ""

# Plugins & Plugin Settings
plugins:             [jekyll-paginate]
paginate:            10

## Excerpt Separator
excerpt_separator:   <!--more-->

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# This is the list of pages to include in the header of the website.
# pages_list:       
#   About:             '/about'
#   Values:            '/values'
#   Articles:          '/articles'
#   Team:              '/team'

defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"

collections:
  projects:
    output: true
  members:
    output: true


pages_list:
  - title: About Us
    subpages:
      - page: Organisation
        url: /about
      - page: Our Values
        url: /values
      - page: Our Team
        url: /team
  - title: Our Work
    subpages:
      - page: Public Finance
        url: /public-finance
      - page: Judiciary
        url: /judiciary
      - page: Education
        url: /education
  - title: Blog
    url: https://www.medium.com/civicdatalab
