source: .
destination:        ./_site
includes:           ./_includes
highlight:           pygments

# Setup
title:               CivicDataLab
tagline:             Data|Tech|Design|Social Science
url:                 https://civicdatalab.in
baseurl:             ""

# Plugins & Plugin Settings
plugins:             [jekyll-paginate]
paginate:            10

## Excerpt Separator
excerpt_separator:   <!--more-->

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# This is the list of pages to include in the header of the website.
# pages_list:       
#   About:             '/about'
#   Values:            '/values'
#   Articles:          '/articles'
#   Team:              '/team'

# all collection folders directory location
collections_dir: all_collections

collections:
  projects:
    permalink: /:collection/:name
    output: true
  members:
    permalink: /:collection/:name
    output: true
  careers:
    output: true
  case_studies:
    permalink: /:collection/:name
    output: true


defaults:
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "case_studies"
    values:
      layout: "case_study"
  - scope:
      path: ""
      type: "careers"
    values:
      layout: "career"